<script setup lang="ts">
import { onBeforeUnmount, onMounted, ref } from 'vue'
import DemoFeed from './DemoFeed.vue'
import PulseLog from './PulseLog.vue'
import { feedModes, probeLive, startLive } from './live'
import type { FeedModes, LiveSnapshot } from './live'
import { DEMO_NOW, PRESEED_FEED, PRESEED_PULSE, STEPS, finalFeed, finalPulse, stamp } from './timeline'
import type { PulseLine } from './timeline'

/**
 * The landing demo: a Laravel app's pulse on the left, the story the feed
 * tells on the right.
 *
 * Two sources, one player. The scripted timeline is the prerender, the
 * fallback, and what plays first; if the Newsroom's docs-demo endpoint
 * answers the probe, the panes switch to LIVE — real activity, generated by
 * the demo app through the real package, so the demo cannot drift from the
 * implementation. If the endpoint is missing or goes quiet, the script
 * resumes and nothing on the page admits an attempt was made.
 *
 * Reduced-motion visitors get the completed scripted story, nothing ticking.
 */
type ShownLine = { time: string; text: string; kind: PulseLine['kind']; status?: number }

const shown = (lines: PulseLine[], cycle: number): ShownLine[] =>
  lines.map((l) => ({
    time: stamp(l.offset, cycle),
    text: l.text,
    kind: l.kind,
    status: l.kind === 'request' ? 201 : undefined,
  }))

// Newest first, both panes — a new beat lands at the same height in each.
const pulse = ref<ShownLine[]>(shown(PRESEED_PULSE, 0).reverse())
const feed = ref<Record<string, any>[]>([...PRESEED_FEED])
const mode = ref<'scripted' | 'live'>('scripted')

/**
 * The read-mode toggles: the same instant re-told at three granularities,
 * which is the read-modes concept demonstrated in one click. Only lit when the
 * endpoint supplies all three; the scripted fallback has one storyline.
 */
const READ_MODES = ['live', 'summary', 'log'] as const
const readMode = ref<(typeof READ_MODES)[number]>('live')
const modes = ref<FeedModes | null>(null)

let timer: ReturnType<typeof setTimeout> | null = null
let stopLive: (() => void) | null = null

function applyLive(snapshot: LiveSnapshot): void {
  pulse.value = snapshot.pulse.slice(0, 14).map((l) => ({
    time: l.at.slice(11, 19),
    text: l.text,
    kind: l.kind,
    status: l.status,
  }))

  modes.value = feedModes(snapshot)
  feed.value = modes.value
    ? modes.value[readMode.value].slice(0, 6)
    : (snapshot.feed.items ?? []).slice(0, 6)
}

function pick(next: (typeof READ_MODES)[number]): void {
  readMode.value = next

  if (modes.value) {
    feed.value = modes.value[next].slice(0, 6)
  }
}

function goLive(first: LiveSnapshot): void {
  if (timer) {
    clearTimeout(timer)
    timer = null
  }

  mode.value = 'live'
  applyLive(first)
  stopLive = startLive(applyLive, () => {
    // The endpoint went quiet: hand back to the script, mid-story.
    stopLive = null
    modes.value = null
    mode.value = 'scripted'
    pulse.value = shown(PRESEED_PULSE, 0).reverse()
    feed.value = [...PRESEED_FEED]
    play(0, 0)
  })
}

function play(index: number, cycle: number): void {
  if (mode.value === 'live') {
    return
  }

  if (index >= STEPS.length) {
    // No reset: the loop wraps, and the story clock rolls forward a cycle so
    // time never runs backwards in the pane.
    play(0, cycle + 1)

    return
  }

  const step = STEPS[index]

  timer = setTimeout(() => {
    pulse.value = [...shown(step.lines, cycle).reverse(), ...pulse.value].slice(0, 14)

    if (step.apply) {
      feed.value = step.apply(feed.value)
    }

    play(index + 1, cycle)
  }, step.delay)
}

onMounted(() => {
  if (window.matchMedia('(prefers-reduced-motion: reduce)').matches) {
    pulse.value = shown(finalPulse(), 0).reverse().slice(0, 14)
    feed.value = finalFeed()

    return
  }

  play(0, 0)

  probeLive().then((snapshot) => {
    if (snapshot) {
      goLive(snapshot)
    }
  })
})

onBeforeUnmount(() => {
  if (timer) {
    clearTimeout(timer)
  }

  stopLive?.()
})
</script>

<template>
  <div class="sf-ticker">
    <section class="sf-ticker__pane sf-ticker__pane--pulse">
      <header class="sf-ticker__label">
        your app
        <span v-if="mode === 'live'" class="sf-ticker__live">● live</span>
      </header>
      <PulseLog :lines="pulse" />
    </section>
    <section class="sf-ticker__pane sf-ticker__pane--story">
      <header class="sf-ticker__label">
        your feed
        <span v-if="mode === 'live' && modes" class="sf-ticker__modes">
          <button
            v-for="m in READ_MODES"
            :key="m"
            type="button"
            class="sf-ticker__mode"
            :class="{ 'sf-ticker__mode--on': readMode === m }"
            @click="pick(m)"
          >{{ m }}</button>
        </span>
      </header>
      <div class="sf-ticker__feed">
        <DemoFeed :key="mode" :items="feed" :pin="mode === 'scripted' ? DEMO_NOW : null" />
      </div>
    </section>
  </div>
</template>

<style scoped>
.sf-ticker {
  display: grid;
  grid-template-columns: minmax(0, 5fr) minmax(0, 7fr);
  gap: 20px;
  margin: 2.5rem 0;
}

@media (max-width: 720px) {
  .sf-ticker {
    grid-template-columns: minmax(0, 1fr);
  }
}

.sf-ticker__pane {
  display: flex;
  flex-direction: column;
  min-height: 380px;
  max-height: 380px;
  border: 1px solid var(--vp-c-divider);
  border-radius: 10px;
  overflow: hidden;
}

.sf-ticker__pane--pulse {
  background: #323b4a;
  border-color: #4b586c;
}

.sf-ticker__pane--story {
  background: var(--vp-c-bg);
}

.sf-ticker__label {
  padding: 8px 16px 7px;
  font-family: var(--vp-font-family-mono);
  font-size: 10px;
  font-weight: 600;
  letter-spacing: 0.09em;
  text-transform: uppercase;
  color: var(--vp-c-text-3);
  border-bottom: 1px solid var(--vp-c-divider);
}

.sf-ticker__pane--pulse .sf-ticker__label {
  color: #97a4b5;
  border-color: #4b586c;
}

.sf-ticker__live {
  margin-left: 8px;
  color: #34d399;
  animation: sf-live-breathe 2.4s ease-in-out infinite;
}

@keyframes sf-live-breathe {
  50% {
    opacity: 0.45;
  }
}

@media (prefers-reduced-motion: reduce) {
  .sf-ticker__live {
    animation: none;
  }
}

.sf-ticker__label {
  display: flex;
  align-items: center;
}

.sf-ticker__modes {
  margin-left: auto;
  display: flex;
  gap: 2px;
}

.sf-ticker__mode {
  padding: 1px 8px;
  border: 0;
  border-radius: 4px;
  background: transparent;
  font: inherit;
  letter-spacing: inherit;
  text-transform: inherit;
  color: var(--vp-c-text-3);
  cursor: pointer;
}

.sf-ticker__mode:hover {
  color: var(--vp-c-text-1);
}

.sf-ticker__mode--on {
  background: var(--vp-c-default-soft);
  color: var(--vp-c-text-1);
}

.sf-ticker__feed {
  flex: 1;
  overflow-y: auto;
  scrollbar-width: thin;
  scrollbar-color: var(--vp-c-divider) transparent;
  padding: 6px 18px 12px;
}

/* Inside the demo the pane is the chrome — strip the docs' output well. */
.sf-ticker__feed :deep(.sf-feed) {
  margin: 0;
  border: 0;
  padding: 0;
  background: transparent;
}

.sf-ticker__feed :deep(.sf-feed)::before {
  content: none;
}
</style>
